import Head from "next/head";
import { Anta, Inter, Trispace } from "next/font/google";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Navbar from "./components/navbar";
import styles from "./agent.module.css";
import { v4 as uuid } from "uuid";
import { getLogs, LogsSchemaType } from "./utils/db";

const antaFont = Anta({
  variable: "--font-anta",
  weight: ["400"],
  subsets: ["latin"],
});

const trispaceFont = Trispace({
  variable: "--font-trispace",
  weight: ["400"],
  subsets: ["latin"],
});

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const Agent = () => {
  const router = useRouter();
  const [currentPath, setCurrentPath] = useState<string>("");
  const [logs, setLogs] = useState<LogsSchemaType>([]);
  const walletAddress = "0x1234567890";
  const signature = "0x1234567890";

  useEffect(() => {
    const current = router.asPath.replace("/", "").toLocaleLowerCase();

    console.log(current);
    if (current === "") {
      setCurrentPath("about");
      return;
    }
    if (current === "agent") {
      setCurrentPath("agent");
      return;
    }
    if (current === "terminal") {
      setCurrentPath("terminal");
      return;
    }
  }, [router.pathname]);

  useEffect(() => {
    getLogs(walletAddress, signature).then((logs) => {
      setLogs(logs);
      console.log(logs);
    });
  }, [walletAddress, signature]);

  return (
    <>
      <Head>
        <title>AIGG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div
        className={`${antaFont.variable} ${trispaceFont.variable} ${interFont.variable} ${styles.main}`}
      >
        <div className={styles.contentContainer}>
          <div className={styles.currPath}>{currentPath}</div>
          <div className={styles.agents}>
            {logs.map((eachLog) => (
              <div key={uuid()} className={styles.agent}>
                <div className={styles.agentTime}>[{eachLog.timestamp}]</div>
                <div className={styles.agentText}>{eachLog.text}</div>
              </div>
            ))}
          </div>

          <img src="/images/castle.png" alt="" className={styles.castle} />
        </div>
      </div>
    </>
  );
};

export default Agent;
