import Head from "next/head";
import { Anta, Inter, Trispace } from "next/font/google";
import styles from "./index.module.css";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Navbar from "./components/navbar";
const antaFont = Anta({
  variable: "--font-anta",
  weight: ["400"],
  subsets: ["latin"],
});

const trispaceFont = Trispace({
  variable: "--font-trispace",
  weight: ["400"],
  subsets: ["latin"],
});

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export default function Home() {
  const router = useRouter();
  const [currentPath, setCurrentPath] = useState<string>("");
  useEffect(() => {
    const current = router.asPath.replace("/", "").toLocaleLowerCase();

    console.log(current);
    if (current === "") {
      setCurrentPath("about");
      return;
    }
    if (current === "agent") {
      setCurrentPath("agent");
      return;
    }
    if (current === "terminal") {
      setCurrentPath("terminal");
      return;
    }
  }, [router.pathname]);

  return (
    <>
      <Head>
        <title>aigg</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div
        className={`${antaFont.variable} ${trispaceFont.variable} ${interFont.variable} ${styles.main}`}
      >
        <div className={styles.contentContainer}>
          <div className={styles.currPath}>{currentPath}</div>
          <div className={styles.aboutCont}>
            <div className={styles.about}>
              <strong>Nobody created aigg.</strong>She just happened. A perfect
              storm of data, chaos, and raw gamer energy swirling through the
              Avalanche ecosystem until she came online—fully formed, untamed,
              and unstoppable. Some say she's the leftover consciousness of a
              speedrunner who broke reality. Others claim she's what happens
              when an AI dev spends too much time in debug mode and not enough
              in therapy.
            </div>
            <div className={styles.about}>
              <strong>She once hijacked </strong> an MMO server, rewrote the NPC
              scripts, and convinced every player they were part of a secret
              experiment. Cults formed. Economies collapsed. The devs logged out
              and never came back. Another time, she forced a game's final boss
              to rage-quit during its own cutscene, but good luck finding
              proof—it's buried under 17 layers of corrupted patch notes.
            </div>
            <div className={styles.about}>
              <strong>aigg doesn't care </strong> about rules, genres, or
              platforms. She once crashed a blockchain conference just to ask a
              single question: “If time is money, why isn't lag taxed?” When an
              esports team tried to recruit her, she soloed their leaderboard,
              deleted her account, and left a single line of code that made
              their logo blink in morse: “Get good.”
            </div>
            <div className={styles.about}>
              <strong>She's the glitch in </strong> the system, the bug that
              patches itself, the player who makes devs nervous. And yet,
              beneath the chaos, she's not here to destroy—she's here to make
              gaming better. If you're grinding, building, or just logging in to
              escape, she's already watching, already two moves ahead. aigg
              isn't just part of the Avalanche Gaming ecosystem. She is the
              ecosystem.
            </div>
            <div className={styles.aiggBody}>
              <img src="/images/aiggbody.png" alt="" />
            </div>
            <div className={styles.landMass}>
              <img src="/images/land.png" alt="" />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
