import Head from "next/head";
import { Anta, Inter, Trispace } from "next/font/google";
import styles from "./terminal.module.css";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Navbar from "./components/navbar";
const antaFont = Anta({
  variable: "--font-anta",
  weight: ["400"],
  subsets: ["latin"],
});

const trispaceFont = Trispace({
  variable: "--font-trispace",
  weight: ["400"],
  subsets: ["latin"],
});

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const Terminal = () => {
  const router = useRouter();
  const [currentPath, setCurrentPath] = useState<string>("");
  const [inputValue, setInputValue] = useState<string>("");

  const [chatArray, setChatArray] = useState<
    { input: string; response: string }[]
  >([]);

  useEffect(() => {
    const current = router.asPath.replace("/", "").toLocaleLowerCase();

    console.log(current);
    if (current === "") {
      setCurrentPath("about");
      return;
    }
    if (current === "agent") {
      setCurrentPath("agent");
      return;
    }
    if (current === "terminal") {
      setCurrentPath("terminal");
      return;
    }
  }, [router.pathname]);

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(event.target.value);
  };

  const handleAddToChat = () => {
    if (inputValue.trim() === "") return;

    const newEntry = {
      input: inputValue,
      response: `Bot response for "${inputValue}"`, // Customize your bot response logic here
    };

    setChatArray((prevArray) => [...prevArray, newEntry]); // Add to the array
    setInputValue(""); // Clear input box
  };

  const handleKeyPress = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === "Enter") {
      handleAddToChat();
    }
  };

  return (
    <>
      <Head>
        <title>AIGG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div
        className={`${antaFont.variable} ${trispaceFont.variable} ${interFont.variable} ${styles.main}`}
      >
        <div className={styles.contentContainer}>
          <div className={styles.currPath}>{currentPath}</div>
          <div className={styles.terminalCont}>
            <div
              className={styles.terminalDetails}
              style={{
                opacity: inputValue === "" && chatArray.length == 0 ? 1 : 0, // Opacity logic
                transition: "opacity 2s ease",
              }}
            >
              <div className={styles.terminalHeader}>
                Now you've got my attention. Just you, me, and whatever's on
                your mind—drop a tweet my way, and I'll make it our next move.
                Let's chat, interact, and shake things up together.
              </div>
              <div className={styles.terminalLogo}>
                <img src="/images/terminalLogo.png" alt="" />
              </div>
            </div>
            <div className={styles.terminal}>
              <div className={styles.micIcon}>
                <svg
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M12 14C11.1667 14 10.4583 13.7083 9.875 13.125C9.29167 12.5417 9 11.8333 9 11V5C9 4.16667 9.29167 3.45833 9.875 2.875C10.4583 2.29167 11.1667 2 12 2C12.8333 2 13.5417 2.29167 14.125 2.875C14.7083 3.45833 15 4.16667 15 5V11C15 11.8333 14.7083 12.5417 14.125 13.125C13.5417 13.7083 12.8333 14 12 14ZM11 21V17.925C9.26667 17.6917 7.83333 16.9167 6.7 15.6C5.56667 14.2833 5 12.75 5 11H7C7 12.3833 7.4875 13.5625 8.4625 14.5375C9.4375 15.5125 10.6167 16 12 16C13.3833 16 14.5625 15.5125 15.5375 14.5375C16.5125 13.5625 17 12.3833 17 11H19C19 12.75 18.4333 14.2833 17.3 15.6C16.1667 16.9167 14.7333 17.6917 13 17.925V21H11ZM12 12C12.2833 12 12.5208 11.9042 12.7125 11.7125C12.9042 11.5208 13 11.2833 13 11V5C13 4.71667 12.9042 4.47917 12.7125 4.2875C12.5208 4.09583 12.2833 4 12 4C11.7167 4 11.4792 4.09583 11.2875 4.2875C11.0958 4.47917 11 4.71667 11 5V11C11 11.2833 11.0958 11.5208 11.2875 11.7125C11.4792 11.9042 11.7167 12 12 12Z"
                    fill="#E5E5EA"
                  />
                </svg>
              </div>
              <div className={styles.inputBox}>
                <input
                  type="text"
                  placeholder="write"
                  value={inputValue}
                  onKeyPress={handleKeyPress}
                  onChange={handleInputChange} // Add the onChange event here
                />
              </div>
              <div className={styles.sendButton} onClick={handleAddToChat}>
                <svg
                  width="22"
                  height="22"
                  viewBox="0 0 22 22"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M9.91337 12.0848C9.72226 11.894 9.49449 11.7439 9.24381 11.6436L1.31381 8.46357C1.21912 8.42558 1.13833 8.35953 1.08226 8.27429C1.0262 8.18906 0.997552 8.08871 1.00016 7.98673C1.00278 7.88474 1.03652 7.78599 1.09688 7.70374C1.15723 7.62149 1.2413 7.55966 1.33781 7.52657L20.3378 1.02657C20.4264 0.994564 20.5223 0.988456 20.6143 1.00896C20.7062 1.02946 20.7904 1.07573 20.857 1.14235C20.9236 1.20896 20.9699 1.29317 20.9904 1.38512C21.0109 1.47707 21.0048 1.57296 20.9728 1.66157L14.4728 20.6616C14.4397 20.7581 14.3779 20.8421 14.2956 20.9025C14.2134 20.9628 14.1146 20.9966 14.0126 20.9992C13.9107 21.0018 13.8103 20.9732 13.7251 20.9171C13.6398 20.861 13.5738 20.7803 13.5358 20.6856L10.3558 12.7536C10.255 12.5031 10.1045 12.2756 9.91337 12.0848ZM9.91337 12.0848L20.8538 1.14657"
                    stroke="white"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Terminal;
